CREATE TABLE [dbo].[CuentasTMP_Listados](
	[nroCuentaTMP] [varchar](50) NOT NULL,
 CONSTRAINT [PK_CuentasTMP_Listados] PRIMARY KEY CLUSTERED 
(
	[nroCuentaTMP] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF